package dumper

import (
	"bufio"
	"context"
	"fmt"
	"html"
	"io"
	"log/slog"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode/utf8"

	"github.com/grzadr/gomper/internal/scanner"
)

// Hook for opening files during streaming, allowing deterministic test error injection.
var openFileHook = func(name string) (*os.File, error) { return os.Open(name) }

// XMLDumper generates XML context representations of codebases.
type XMLDumper struct {
	logger *slog.Logger
}

// NewXMLDumper creates a new dumper instance.
func NewXMLDumper(logger *slog.Logger) *XMLDumper {
	if logger == nil {
		logger = slog.Default()
	}
	return &XMLDumper{logger: logger}
}

// FileMetadata holds extracted metadata for a single file.
type FileMetadata struct {
	Path    string
	RelPath string
	Lang    string
	Tokens  int
}

// EstimateTokens calculates an approximate token count for file content (~4 chars per token).
func EstimateTokens(content []byte) int {
	if len(content) == 0 {
		return 0
	}
	return (len(content) + 3) / 4
}

// FormatLineNumberedContent reads from r line by line, prepends 1-indexed line numbers ("1 | ..."),
// optionally applies XML escaping, and writes formatted output directly to w.
func FormatLineNumberedContent(r io.Reader, w io.Writer, escapeXML bool) error {
	scanner := bufio.NewScanner(r)
	buf := make([]byte, 64*1024)
	scanner.Buffer(buf, 10*1024*1024)

	lineNum := 1
	for scanner.Scan() {
		line := scanner.Text()
		if escapeXML {
			line = html.EscapeString(line)
		}
		if _, err := fmt.Fprintf(w, "%d | %s\n", lineNum, line); err != nil {
			return err
		}
		lineNum++
	}
	return scanner.Err()
}

// TreeNode represents a node in the directory structure hierarchy.
type TreeNode struct {
	Name     string
	IsDir    bool
	Children map[string]*TreeNode
}

// BuildDirectoryTree generates an indented string representation of scanned entries.
func BuildDirectoryTree(entries []scanner.Entry) string {
	root := &TreeNode{Children: make(map[string]*TreeNode)}

	for _, entry := range entries {
		rel := filepath.ToSlash(entry.RelPath)
		if rel == "." || rel == "" {
			continue
		}

		parts := strings.Split(rel, "/")
		curr := root
		for i, part := range parts {
			if part == "" {
				continue
			}
			isLast := (i == len(parts)-1)
			isDir := !isLast || entry.IsDir

			child, exists := curr.Children[part]
			if !exists {
				child = &TreeNode{
					Name:     part,
					IsDir:    isDir,
					Children: make(map[string]*TreeNode),
				}
				curr.Children[part] = child
			} else if isDir {
				child.IsDir = true
			}
			curr = child
		}
	}

	var sb strings.Builder
	renderTree(root, 0, &sb)
	return sb.String()
}

func renderTree(node *TreeNode, depth int, sb *strings.Builder) {
	names := make([]string, 0, len(node.Children))
	for name := range node.Children {
		names = append(names, name)
	}
	sort.Strings(names)

	indent := strings.Repeat("  ", depth)
	for _, name := range names {
		child := node.Children[name]
		if child.IsDir {
			fmt.Fprintf(sb, "%s%s/\n", indent, child.Name)
			renderTree(child, depth+1, sb)
		} else {
			fmt.Fprintf(sb, "%s%s\n", indent, child.Name)
		}
	}
}

func (d *XMLDumper) collectMetadata(ctx context.Context, entries []scanner.Entry) ([]FileMetadata, int, error) {
	var metas []FileMetadata
	totalTokens := 0

	for _, entry := range entries {
		if ctx.Err() != nil {
			return nil, 0, ctx.Err()
		}

		if entry.IsDir {
			continue
		}

		lang, known := scanner.LookupLanguage(entry.Path)
		if !known {
			ext := filepath.Ext(entry.Path)
			d.logger.InfoContext(ctx, "unsupported file extension encountered",
				slog.String("path", entry.Path),
				slog.String("ext", ext),
			)
		}

		rawContent, err := os.ReadFile(entry.Path)
		if err != nil {
			d.logger.WarnContext(ctx, "unable to read file content for dump",
				slog.String("path", entry.Path),
				slog.Any("error", err),
			)
			continue
		}

		if !utf8.Valid(rawContent) {
			d.logger.DebugContext(ctx, "skipping non-UTF8 binary file", slog.String("path", entry.Path))
			continue
		}

		tokens := EstimateTokens(rawContent)
		totalTokens += tokens

		relPath := filepath.ToSlash(entry.RelPath)
		if relPath == "" || relPath == "." {
			relPath = filepath.Base(entry.Path)
		}

		metas = append(metas, FileMetadata{
			Path:    entry.Path,
			RelPath: relPath,
			Lang:    lang,
			Tokens:  tokens,
		})
	}

	return metas, totalTokens, nil
}

// GenerateXML writes the XML document for the provided scanned entries to targetWriter.
func (d *XMLDumper) GenerateXML(ctx context.Context, entries []scanner.Entry, instructions string, targetWriter io.Writer) error {
	metas, totalTokens, err := d.collectMetadata(ctx, entries)
	if err != nil {
		return err
	}

	dirTree := BuildDirectoryTree(entries)

	w := bufio.NewWriter(targetWriter)
	defer func() { _ = w.Flush() }()

	_, _ = fmt.Fprintln(w, `<codebase_context version="1.0">`)
	_, _ = fmt.Fprintln(w, `<header>`)
	_, _ = fmt.Fprintln(w, `  <summary>`)
	_, _ = fmt.Fprintln(w, `    <generation_info>Generated by Automated Repository Packer</generation_info>`)
	_, _ = fmt.Fprintln(w, `    <purpose>Merged representation of the codebase for automated code review, refactoring, or feature implementation.</purpose>`)
	_, _ = fmt.Fprintf(w, "    <total_files>%d</total_files>\n", len(metas))
	_, _ = fmt.Fprintf(w, "    <total_tokens>%d</total_tokens>\n", totalTokens)
	_, _ = fmt.Fprintln(w, `  </summary>`)
	_, _ = fmt.Fprintln(w, `  <usage_guidelines>`)
	_, _ = fmt.Fprintln(w, `    - Treat this document as a read-only repository snapshot.`)
	_, _ = fmt.Fprintln(w, `    - Reference specific files using their full relative paths as defined in the path attribute.`)
	_, _ = fmt.Fprintln(w, `    - When generating code changes, specify line numbers or provide complete functional blocks.`)
	_, _ = fmt.Fprintln(w, `  </usage_guidelines>`)
	_, _ = fmt.Fprintln(w, `  <user_instructions>`)
	if instructions != "" {
		_, _ = fmt.Fprintf(w, "    %s\n", html.EscapeString(instructions))
	}
	_, _ = fmt.Fprintln(w, `  </user_instructions>`)
	_, _ = fmt.Fprintln(w, `</header>`)
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, `<directory_structure>`)
	_, _ = w.WriteString(dirTree)
	_, _ = fmt.Fprintln(w, `</directory_structure>`)
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, `<files>`)

	for _, meta := range metas {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		_, _ = fmt.Fprintf(w, "  <file path=%q language=%q tokens=\"%d\">\n", meta.RelPath, meta.Lang, meta.Tokens)
		err := func() error {
			file, err := openFileHook(meta.Path)
			if err != nil {
				return err
			}
			defer func() { _ = file.Close() }()
			return FormatLineNumberedContent(file, w, true)
		}()
		if err != nil {
			d.logger.WarnContext(ctx, "unable to stream file content for dump",
				slog.String("path", meta.Path),
				slog.Any("error", err),
			)
		}
		_, _ = fmt.Fprintln(w, `  </file>`)
	}

	_, _ = fmt.Fprintln(w, `</files>`)
	_, _ = fmt.Fprintln(w, `</codebase_context>`)

	return w.Flush()
}

// GenerateMarkdown writes a Markdown document representation for scanned entries to targetWriter.
func (d *XMLDumper) GenerateMarkdown(ctx context.Context, entries []scanner.Entry, instructions string, targetWriter io.Writer) error {
	metas, totalTokens, err := d.collectMetadata(ctx, entries)
	if err != nil {
		return err
	}

	dirTree := BuildDirectoryTree(entries)

	w := bufio.NewWriter(targetWriter)
	defer func() { _ = w.Flush() }()

	_, _ = fmt.Fprintln(w, `# Codebase Context (v1.0)`)
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, `## Header`)
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, `### Summary`)
	_, _ = fmt.Fprintln(w, `- **Generation Info**: Generated by Automated Repository Packer`)
	_, _ = fmt.Fprintln(w, `- **Purpose**: Merged representation of the codebase for automated code review, refactoring, or feature implementation.`)
	_, _ = fmt.Fprintf(w, "- **Total Files**: %d\n", len(metas))
	_, _ = fmt.Fprintf(w, "- **Total Tokens**: %d\n", totalTokens)
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, `### Usage Guidelines`)
	_, _ = fmt.Fprintln(w, `- Treat this document as a read-only repository snapshot.`)
	_, _ = fmt.Fprintln(w, `- Reference specific files using their full relative paths as defined in the path attribute.`)
	_, _ = fmt.Fprintln(w, `- When generating code changes, specify line numbers or provide complete functional blocks.`)
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, `### User Instructions`)
	if instructions != "" {
		_, _ = fmt.Fprintln(w, instructions)
	} else {
		_, _ = fmt.Fprintln(w, `None`)
	}
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, `## Directory Structure`)
	_, _ = fmt.Fprintln(w, "```")
	_, _ = w.WriteString(dirTree)
	_, _ = fmt.Fprintln(w, "```")
	_, _ = fmt.Fprintln(w)
	_, _ = fmt.Fprintln(w, `## Files`)
	_, _ = fmt.Fprintln(w)

	for _, meta := range metas {
		if ctx.Err() != nil {
			return ctx.Err()
		}
		_, _ = fmt.Fprintf(w, "### File: `%s`\n", meta.RelPath)
		_, _ = fmt.Fprintf(w, "- **Language**: %s\n", meta.Lang)
		_, _ = fmt.Fprintf(w, "- **Tokens**: %d\n\n", meta.Tokens)
		_, _ = fmt.Fprintf(w, "```%s\n", meta.Lang)
		err := func() error {
			file, err := openFileHook(meta.Path)
			if err != nil {
				return err
			}
			defer func() { _ = file.Close() }()
			return FormatLineNumberedContent(file, w, false)
		}()
		if err != nil {
			d.logger.WarnContext(ctx, "unable to stream file content for dump",
				slog.String("path", meta.Path),
				slog.Any("error", err),
			)
		}
		_, _ = fmt.Fprintln(w, "```")
		_, _ = fmt.Fprintln(w)
	}

	return w.Flush()
}
